Fix setup.py version import in CMakeLists
When running `run_developer_setup.sh`:

```
...
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'setup' has no attribute 'version'
ERRORFailed when running python code: """
import setup; print(setup.version)"""
CMake Error at CMakeLists.txt:24 (message):
  Python command failed with error code: 1
Call Stack (most recent call first):
  CMakeLists.txt:30 (_pycmd)

-- Configuring incomplete, errors occurred!
```

It looks like `setup.py` has a variable called `VERSION` instead of `version`
so change `setup.version` to `setup.VERSION`.